using Volo.Abp;

namespace AbpUserVerificationByEmail.EntityFrameworkCore;

public abstract class AbpUserVerificationByEmailEntityFrameworkCoreTestBase : AbpUserVerificationByEmailTestBase<AbpUserVerificationByEmailEntityFrameworkCoreTestModule>
{

}
